=== priyabelhekar2697/WebTech/XML/xmlvalidation/ass1dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT CDCatlogs (CD)+>
<!ELEMENT CD (title,Artist+,Compony?,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT Artist (#PCDATA)>
<!ELEMENT Compony (#PCDATA)>
<!ELEMENT price (#PCDATA)>


<!ATTLIST CD lang (Hindi|English|Marathi) #REQUIRED>

=== priyabelhekar2697/WebTech/XML/xmlvalidation/ass1xml.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE CDCatlogs SYSTEM "ass1dtd.dtd"><CDCatlogs>	<CD lang="English">		<title>POP Songs</title>		<Artist>Honey Singh</Artist>		<Compony>T-series</Compony>		<price>500</price>	</CD>	<CD lang="Hindi">		<title>POP Songs</title>		<Artist>Neha Kakkar</Artist>		<Compony>T-series</Compony>		<price>1000</price>	</CD></CDCatlogs>
