=== priyabelhekar2697/WebTech/XML/xmlvalidation/ass2dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT RECIPEs (Recipe)>
<!ELEMENT Recipe (Name, Desc, Ingrident+, intstruction)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Desc (#PCDATA)>
<!ELEMENT Ingrident (item, quantity)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT intstruction (step)+>
<!ELEMENT step (#PCDATA)>
<!ATTLIST Name
	Type (Main_course | Starter | SweetDish) #REQUIRED
>
<!ATTLIST quantity
	unit (gram | Liter | Tea-spoon | Table-spoon) "gram"
>

=== priyabelhekar2697/WebTech/XML/xmlvalidation/ass2xml.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE RECIPEs SYSTEM "ass2dtd.dtd"><RECIPEs>	<Recipe>		<Name Type="Starter">Panner Chillie</Name>		<Desc>It is the Panner item.</Desc>		<Ingrident>			<item>&quot;Panner &quot;onion &quot;Ginger &quot;Garlic</item>			<quantity unit="gram">300</quantity>		</Ingrident>		<intstruction>			<step>Serving Suggestions: Serve chilli paneer with 						fried rice or schezwan fried rice or burnt garlic fried rice.						It also goes well as a side dish with pulao or jeera rice or ghee rice. 						You can also have it with tandoori roti or naan or roomali roti. You can even have it 						as an appetizer snack with any chinese dipping sauce.				</step>		</intstruction>	</Recipe></RECIPEs>
