=== priyabelhekar2697/WebTech/XML/xmlvalidation/ass3dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Compony (Employee)+>
<!ELEMENT Employee (Name,EmployeeId,Salary,Contact+,Email+,Dbirth,Department)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT EmployeeId (#PCDATA)>
<!ELEMENT Salary (Basic,Allownces*)>
<!ELEMENT Basic (#PCDATA)>
<!ELEMENT Allownces (#PCDATA)>
<!ELEMENT Contact (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Dbirth (#PCDATA)>
<!ELEMENT Department (#PCDATA)>

<!ATTLIST Employee designation CDATA #IMPLIED>
<!ATTLIST Basic unit CDATA "rs">
<!ATTLIST Allownces unit CDATA "rs">
<!ATTLIST Allownces type (TA|DA|Extra|HRA) #REQUIRED>

=== priyabelhekar2697/WebTech/XML/xmlvalidation/ass3xml.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Compony SYSTEM "ass3dtd.dtd"><Compony>	<Employee designation="Manager">		<Name>Priyanka Belhekar</Name>		<EmployeeId>100</EmployeeId>		<Salary>			<Basic unit="rs">30000</Basic>			<Allownces type="Extra" unit="rs">5000</Allownces>		</Salary>		<Contact>9527986037</Contact>		<Email>priyabelhekar26@gmail.com</Email>		<Dbirth>26th July,1997</Dbirth>		<Department>HR</Department>	</Employee></Compony>
